version: '3.5'

services:
  
  prometheus:
    image: prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9000:9090
    build:
      context: .
      dockerfile: Dockerfile_prometheus
    networks:
      prometheus:
        ipv4_address: 1.1.1.5

  grafana: 
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 2700:3000
    networks:
      prometheus:
        ipv4_address: 1.1.1.2
  
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - '/proc:/host/proc'
      - '/sys:/host/sys'
      - '/:/rootfs'
      - '/home:/home'
    networks:
      prometheus:
        ipv4_address: 1.1.1.3

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    networks:
      prometheus:
        ipv4_address: 1.1.1.4

  postgres:
    image: postgres:9.6
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: meocon
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    networks:
      prometheus:
        ipv4_address: 1.1.1.6

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    restart: always
    container_name: meocon_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://meocon:123@1.1.1.6:5432/postgres?sslmode=disable"
    ports:
      - 9187:9187
    networks:
      prometheus:
        ipv4_address: 1.1.1.7

  adminer:
    image: adminer
    ports:
      - 8777:8080
    restart: always
    networks:
      prometheus:
        ipv4_address: 1.1.1.8

  go_custom:
    image: go_custom
    restart: always
    container_name: go_custom
    build:
      context: .
      dockerfile: Dockerfile_go_exporter
    ports:
      - 9876:9876
    networks:
      prometheus:
        ipv4_address: 1.1.1.9

  lua_nginx:
    image: lua_nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - 9145:9145
    networks:
      prometheus:
        ipv4_address: 1.1.1.10


networks:
  prometheus:
    name: prometheus-nw
    ipam:
      driver: default
      config:
        - subnet: 1.1.1.0/24