global:
  # Every 15s get metrics from monitoring targets
  scrape_interval:     5s
  # Each 10s run expresions defined in alert rule and update alert state
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['1.1.1.5:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['1.1.1.3:9100']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['1.1.1.4:8080']
  
  - job_name: 'database'
    static_configs:
    - targets: ['1.1.1.7:9187']

  - job_name: 'web'
    static_configs:
    - targets: ['1.1.1.10:9145', '1.1.1.9:9876']
